// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (name, credentials, type, enabled)
VALUES ($1, $2, $3, $4)
RETURNING id, name, credentials, type, enabled
`

type CreateChannelParams struct {
	Name        string
	Credentials string
	Type        ChannelType
	Enabled     bool
}

type CreateChannelRow struct {
	ID          pgtype.UUID
	Name        string
	Credentials string
	Type        ChannelType
	Enabled     bool
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (CreateChannelRow, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.Name,
		arg.Credentials,
		arg.Type,
		arg.Enabled,
	)
	var i CreateChannelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Credentials,
		&i.Type,
		&i.Enabled,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE
FROM channels
WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveChannels = `-- name: GetActiveChannels :many
SELECT id, type, credentials, name
FROM channels
WHERE enabled = true
`

type GetActiveChannelsRow struct {
	ID          pgtype.UUID
	Type        ChannelType
	Credentials string
	Name        string
}

func (q *Queries) GetActiveChannels(ctx context.Context) ([]GetActiveChannelsRow, error) {
	rows, err := q.db.Query(ctx, getActiveChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveChannelsRow
	for rows.Next() {
		var i GetActiveChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Credentials,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannel = `-- name: GetChannel :one
SELECT id, type, credentials, name, enabled
FROM channels
WHERE id = $1
`

type GetChannelRow struct {
	ID          pgtype.UUID
	Type        ChannelType
	Credentials string
	Name        string
	Enabled     bool
}

func (q *Queries) GetChannel(ctx context.Context, id pgtype.UUID) (GetChannelRow, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i GetChannelRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Credentials,
		&i.Name,
		&i.Enabled,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, type, credentials, name, enabled
FROM channels
`

type ListChannelsRow struct {
	ID          pgtype.UUID
	Type        ChannelType
	Credentials string
	Name        string
	Enabled     bool
}

func (q *Queries) ListChannels(ctx context.Context) ([]ListChannelsRow, error) {
	rows, err := q.db.Query(ctx, listChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChannelsRow
	for rows.Next() {
		var i ListChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Credentials,
			&i.Name,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
SET name        = $2,
    credentials = $3,
    type        = $4,
    enabled     = $5
WHERE id = $1
RETURNING id, name, credentials, type, enabled
`

type UpdateChannelParams struct {
	ID          pgtype.UUID
	Name        string
	Credentials string
	Type        ChannelType
	Enabled     bool
}

type UpdateChannelRow struct {
	ID          pgtype.UUID
	Name        string
	Credentials string
	Type        ChannelType
	Enabled     bool
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (UpdateChannelRow, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.ID,
		arg.Name,
		arg.Credentials,
		arg.Type,
		arg.Enabled,
	)
	var i UpdateChannelRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Credentials,
		&i.Type,
		&i.Enabled,
	)
	return i, err
}
